name = "plfl"
defaultTargets = ["plfl"]

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "main"

[[lean_lib]]
name = "Book"

[[lean_exe]]
name = "plfl"
root = "BookMain"

